# Generated by Django 5.1.15 on 2026-10-05 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official name of the school institution.', max_length=255)),
                ('slug', models.SlugField(help_text='Subdomain identifier.', max_length=100, unique=True)),
                ('contact_email', models.EmailField(help_text='Primary administrative contact email.', max_length=254)),
                ('contact_phone', models.CharField(help_text='Official contact phone number.', max_length=32)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(default='Lahore', max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=64)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=64)),
                ('logo', models.URLField(blank=True, null=True)),
                ('brand_primary_color', models.CharField(default='#2563EB', help_text='Hex code for primary brand color.', max_length=7)),
                ('brand_accent_color', models.CharField(default='#F59E0B', help_text='Hex code for secondary accent color.', max_length=7)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this school subscription is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.school')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Campus', max_length=255)),
                ('code', models.CharField(default='MAIN', max_length=32)),
                ('address', models.TextField(blank=True, default='')),
                ('is_main', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='core.school')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SchoolAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, help_text='Associated campus branch (defaults to main campus in MVP).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.campus')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'School Announcement',
                'verbose_name_plural': 'School Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
