# Generated by Django 5.1.15 on 2026-10-06 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='has_sample_data',
            field=models.BooleanField(default=False, help_text='Indicates whether sample test data has been populated.'),
        ),
        migrations.AddField(
            model_name='school',
            name='is_demo_school',
            field=models.BooleanField(default=False, help_text='Identifies pre-seeded demonstration schools.'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_username', models.CharField(max_length=150)),
                ('actor_role', models.CharField(max_length=32)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, help_text='Associated campus branch (defaults to main campus in MVP).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.campus')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Session name e.g. '2026-2027' or 'Fall 2026'.", max_length=100)),
                ('start_date', models.DateField(help_text='Session starting date.')),
                ('end_date', models.DateField(help_text='Session concluding date.')),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Marks this session as the active academic term.')),
                ('is_closed', models.BooleanField(default=False, help_text='Indicates an archived session where modifications are locked.')),
                ('campus', models.ForeignKey(blank=True, help_text='Associated campus branch (defaults to main campus in MVP).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.campus')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'ordering': ['-start_date'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolRolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(db_index=True, help_text='System role identifier.', max_length=32)),
                ('can_manage_academics', models.BooleanField(default=False)),
                ('can_create_timetable', models.BooleanField(default=False)),
                ('can_mark_attendance', models.BooleanField(default=False)),
                ('can_enter_marks', models.BooleanField(default=False)),
                ('can_collect_fees', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(blank=True, help_text='Associated campus branch (defaults to main campus in MVP).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.campus')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'unique_together': {('school', 'role')},
            },
        ),
    ]
