# Generated by Django 5.1.15 on 2026-10-07 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apply_row_level_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRegistrationDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(db_index=True, max_length=254)),
                ('school_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('data', models.JSONField(default=dict, help_text='Complete registration wizard payload.')),
                ('code_hash', models.CharField(help_text='SHA-256 hash of 6-digit email verification code.', max_length=128)),
                ('expires_at', models.DateTimeField(help_text='Verification code expiration timestamp (10 minutes).')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Verification attempts (max 5).')),
                ('last_sent_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last code dispatch for 60s cooldown.')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration Draft',
                'verbose_name_plural': 'Registration Drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='allow_google_login',
            field=models.BooleanField(default=True, help_text='Whether staff and students may authenticate via Google OAuth.'),
        ),
        migrations.AddField(
            model_name='school',
            name='board',
            field=models.CharField(default='bise_lahore', help_text='Affiliated education board e.g. fbise, bise_lahore, cambridge_caie', max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='gender_type',
            field=models.CharField(default='co_education', help_text='co_education, boys_only, girls_only', max_length=32),
        ),
        migrations.AddField(
            model_name='school',
            name='levels',
            field=models.CharField(default='playgroup_to_matric', help_text='Educational grade levels offered', max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='medium_of_instruction',
            field=models.CharField(default='english', help_text='english, urdu, bilingual', max_length=32),
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.CharField(default='Punjab', max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(default='private', help_text='e.g. private, semi_government, cambridge', max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_approval', 'Pending Superadmin Approval'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=32),
        ),
        migrations.AddField(
            model_name='school',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='terms_version',
            field=models.CharField(default='v1.0', max_length=32),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
