# Generated by Django 5.1.15 on 2026-10-07 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schoolregistrationdraft_school_allow_google_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolregistrationdraft',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of last code dispatch for 60s cooldown.'),
        ),
    ]
