# Generated by Django 5.1.15 on 2026-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Requires user to set a new password on their first login.'),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_password_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
