# Generated by Django 5.1.15 on 2026-10-07 12:54

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0003_user_must_change_password_and_more'),
        ('core', '0004_schoolregistrationdraft_school_allow_google_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentStudentRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], default='guardian', max_length=32)),
            ],
            options={
                'verbose_name': 'Parent Student Relation',
                'verbose_name_plural': 'Parent Student Relations',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=1, help_text='Incremented to force logout all sessions.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email address (optional for students and parents).', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Case-insensitive unique within school.', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), models.F('school'), condition=models.Q(('school__isnull', False)), name='unique_lower_username_per_school'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), condition=models.Q(('school__isnull', True)), name='unique_lower_global_username'),
        ),
        migrations.AddField(
            model_name='parentstudentrelation',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Associated campus branch (defaults to main campus in MVP).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.campus'),
        ),
        migrations.AddField(
            model_name='parentstudentrelation',
            name='parent',
            field=models.ForeignKey(help_text='Parent / Guardian user account.', on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentstudentrelation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school'),
        ),
        migrations.AddField(
            model_name='parentstudentrelation',
            name='student',
            field=models.ForeignKey(help_text='Student user account.', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='parentstudentrelation',
            unique_together={('school', 'parent', 'student')},
        ),
    ]
